# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - staging
#       - production

# jobs:
#   ci:
#     name: Run Tests
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout código
#         uses: actions/checkout@v3

#       - name: Instalar dependências
#         run: |
#           npm install

#       - name: Executar testes
#         run: |
#           npm test

#   cd:
#     name: Build & Push Docker Image
#     needs: ci  # Só roda se o CI passar
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout código
#         uses: actions/checkout@v3

#       - name: Login no Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Construir e enviar imagem para Docker Hub
#         run: |
#           REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)  # Extrai o nome do repositório
#           BRANCH_NAME=${{ github.ref_name }}

#           if [[ "$BRANCH_NAME" == "staging" ]]; then
#             TAG="staging"
#           elif [[ "$BRANCH_NAME" == "production" ]]; then
#             TAG="production"
#           else
#             echo "Branch inválida para deploy."
#             exit 1
#           fi

#           echo "Construindo imagem ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:$TAG"

#           docker build -t ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:$TAG .
#           docker push ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:$TAG
